/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba.practica1_lfp;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author mario
 */
public class FramePrincipal extends javax.swing.JFrame {

    private File archivo;
    private MotorAnalizador motor;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    public File getArchivo() {
        return archivo;
    }

    public JTable getTableTokensCorrectos() {
        return TableTokensCorrectos;
    }

    public JTable getTableTokensIncorrectos() {
        return TableTokensIncorrectos;
    }

    public void setMotor(MotorAnalizador motor) {
        this.motor = motor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableTokensCorrectos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableTokensIncorrectos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCargarArchvio = new javax.swing.JMenu();
        btnTokensCorrectosHTml = new javax.swing.JMenu();
        btnTokensIncorrectosHtml = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableTokensCorrectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "LEXEMA", "TIPO", "FILA", "COLUMNA"
            }
        ));
        jScrollPane1.setViewportView(TableTokensCorrectos);

        TableTokensIncorrectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NUMERO", "LEXEMA", "TIPO", "FILA", "COLUMNA"
            }
        ));
        jScrollPane3.setViewportView(TableTokensIncorrectos);

        btnCargarArchvio.setText("Cargar archivo");
        btnCargarArchvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarArchvioMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCargarArchvio);

        btnTokensCorrectosHTml.setText("Importar html tokens correctos");
        jMenuBar1.add(btnTokensCorrectosHTml);

        btnTokensIncorrectosHtml.setText("Importar html tokens incorrectos");
        jMenuBar1.add(btnTokensIncorrectosHtml);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarArchvioMouseClicked
        JFileChooser seleccionar = new JFileChooser();
        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            archivo = seleccionar.getSelectedFile();
            String nombreArchivo = archivo.getName();
            if (nombreArchivo.endsWith(".pz")) {
                motor.cargarArchivo();
            }else{
                JOptionPane.showConfirmDialog(null, "FORMATO DE ARCHIVO INCORRECTO");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el archivo");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarArchvioMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTokensCorrectos;
    private javax.swing.JTable TableTokensIncorrectos;
    private javax.swing.JMenu btnCargarArchvio;
    private javax.swing.JMenu btnTokensCorrectosHTml;
    private javax.swing.JMenu btnTokensIncorrectosHtml;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
