/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba.practica1_lfp;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author mario
 */
public class FramePrincipal extends javax.swing.JFrame {

    private File archivoFile;
    private MotorAnalizador motor;
    private String direccionHtml;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        this.setResizable(false);
    }

    public File getArchivo() {
        return archivoFile;
    }

    public JTable getTableTokensCorrectos() {
        return TableTokensCorrectos;
    }

    public JTable getTableTokensIncorrectos() {
        return TableTokensIncorrectos;
    }

    public void setMotor(MotorAnalizador motor) {
        this.motor = motor;
    }

    public String getDireccionHtml() {
        return direccionHtml;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableTokensCorrectos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableTokensIncorrectos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCargarArchvio = new javax.swing.JMenu();
        btnAnalizar = new javax.swing.JMenu();
        btnGuardar = new javax.swing.JMenu();
        btnTokensCorrectosHTml = new javax.swing.JMenu();
        btnTokensIncorrectosHtml = new javax.swing.JMenu();
        btnReporteEstadisticas = new javax.swing.JMenu();
        btnImagenAfd = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));

        TableTokensCorrectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "LEXEMA", "TIPO", "FILA", "COLUMNA"
            }
        ));
        jScrollPane1.setViewportView(TableTokensCorrectos);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 153));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 204));

        TableTokensIncorrectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NUMERO", "LEXEMA", "TIPO", "FILA", "COLUMNA"
            }
        ));
        jScrollPane3.setViewportView(TableTokensIncorrectos);

        txtAreaTexto.setColumns(20);
        txtAreaTexto.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaTexto.setRows(5);
        jScrollPane2.setViewportView(txtAreaTexto);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargarArchvio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCargarArchvio.setText("Cargar archivo");
        btnCargarArchvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarArchvioMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnCargarArchvio);

        btnAnalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAnalizar.setText("analizar");
        btnAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnalizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnAnalizar);

        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardar.setText("Guardar archivo");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnGuardar);

        btnTokensCorrectosHTml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTokensCorrectosHTml.setText("Importar html tokens correctos");
        btnTokensCorrectosHTml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTokensCorrectosHTmlMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnTokensCorrectosHTml);

        btnTokensIncorrectosHtml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTokensIncorrectosHtml.setText("Importar html tokens incorrectos");
        btnTokensIncorrectosHtml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTokensIncorrectosHtmlMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnTokensIncorrectosHtml);

        btnReporteEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReporteEstadisticas.setText("Reporte estadisticas");
        btnReporteEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteEstadisticasMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnReporteEstadisticas);

        btnImagenAfd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImagenAfd.setText("Imagen AFD");
        btnImagenAfd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImagenAfdMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnImagenAfd);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarArchvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarArchvioMouseClicked
        JFileChooser seleccionar = new JFileChooser();
        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            archivoFile = seleccionar.getSelectedFile();
            String nombreArchivo = archivoFile.getName();
            if (nombreArchivo.endsWith(".pz")) {
                motor.cargarArchivo();
            } else {
                JOptionPane.showMessageDialog(null, "FORMATO DE ARCHIVO INCORRECTO");
            }

        } else {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el archivo");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarArchvioMouseClicked

    public JTextArea getTxtAreaTexto() {
        return txtAreaTexto;
    }

    private void btnTokensCorrectosHTmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTokensCorrectosHTmlMouseClicked
        String nombre = JOptionPane.showInputDialog("Introduce tu nombre:");
        if (nombre == null) {
            return;
        }
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File carpeta = seleccionar.getSelectedFile();
            direccionHtml = carpeta.getAbsolutePath();
            motor.crearHtmlTokensCorrectos(nombre);

        } else {

            JOptionPane.showMessageDialog(null, "No se puede crear el archivo html");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnTokensCorrectosHTmlMouseClicked

    private void btnTokensIncorrectosHtmlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTokensIncorrectosHtmlMouseClicked
        String nombre = JOptionPane.showInputDialog("Introduce tu nombre:");
        if (nombre == null) {
            return;
        }
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File carpeta = seleccionar.getSelectedFile();
            direccionHtml = carpeta.getAbsolutePath();
            motor.crearHtmlTokensIncorrectos(nombre);

        } else {
            JOptionPane.showMessageDialog(null, "No se puede crear el archivo html");
        }
// TODO add 

// TODO add your handling code here:
    }//GEN-LAST:event_btnTokensIncorrectosHtmlMouseClicked

    private void btnAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalizarMouseClicked

        motor.analizarArchivo();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String nombre = JOptionPane.showInputDialog("Introduce un nombre para el archivo:");
        if (nombre == null) {
            return;
        }
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File carpeta = seleccionar.getSelectedFile();
            direccionHtml = carpeta.getAbsolutePath();
            motor.crearPz(nombre);

        } else {
            JOptionPane.showMessageDialog(null, "No se puede crear el archivo html");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnImagenAfdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImagenAfdMouseClicked

        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File carpeta = seleccionar.getSelectedFile();
            direccionHtml = carpeta.getAbsolutePath();
            motor.generarImagen();

        } else {
            JOptionPane.showMessageDialog(null, "No se puede crear el archivo html");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnImagenAfdMouseClicked

    private void btnReporteEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteEstadisticasMouseClicked
 String nombre = JOptionPane.showInputDialog("Introduce un nombre para el archivo:");
        if (nombre == null) {
            return;
        }
        JFileChooser seleccionar = new JFileChooser();
        seleccionar.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int resultado = seleccionar.showOpenDialog(null);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            File carpeta = seleccionar.getSelectedFile();
            direccionHtml = carpeta.getAbsolutePath();
            motor.crearEstadisitca(nombre);

        } else {
            JOptionPane.showMessageDialog(null, "No se puede crear el archivo html");
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_btnReporteEstadisticasMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTokensCorrectos;
    private javax.swing.JTable TableTokensIncorrectos;
    private javax.swing.JMenu btnAnalizar;
    private javax.swing.JMenu btnCargarArchvio;
    private javax.swing.JMenu btnGuardar;
    private javax.swing.JMenu btnImagenAfd;
    private javax.swing.JMenu btnReporteEstadisticas;
    private javax.swing.JMenu btnTokensCorrectosHTml;
    private javax.swing.JMenu btnTokensIncorrectosHtml;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAreaTexto;
    // End of variables declaration//GEN-END:variables
}
